using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Confess.Database.Models.Tables
{
    public class SignalrConnection
    {
        #region Relationship

        /// <summary>
        ///     Owner of connection.
        /// </summary>
        [JsonIgnore]
        [ForeignKey(nameof(OwnerIndex))]
        public Account Owner { get; set; }

        #endregion

        #region Properties

        /// <summary>
        ///     Connection index (auto generated by SignalR)
        /// </summary>
        [Key]
        public string Index { get; set; }

        /// <summary>
        ///     Index of account which created the connection.
        /// </summary>
        public int OwnerIndex { get; set; }

        /// <summary>
        ///     When the connection was created.
        /// </summary>
        public double Created { get; set; }

        #endregion
    }
}