namespace iConfess.Database.Models.Tables
{
    public class SignalrConnection
    {
        #region Properties

        /// <summary>
        /// Connection index (auto generated by SignalR)
        /// </summary>
        public string Index { get; set; }

        /// <summary>
        /// Index of account which created the connection.
        /// </summary>
        public int OwnerIndex { get; set; }

        /// <summary>
        /// When the connection was created.
        /// </summary>
        public double Created { get; set; }

        #endregion

        #region Relationship

        /// <summary>
        /// Owner of connection.
        /// </summary>
        public Account Owner { get; set; }

        #endregion
    }
}