using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Models.Tables
{
    [Table(nameof(Comment))]
    public class Comment
    {
        #region Properties

        /// <summary>
        ///     Index of comment (auto-generated by database)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        ///     Index of owner who created comment.
        /// </summary>
        public int Owner { get; set; }

        /// <summary>
        ///     Index of post which comment belongs to.
        /// </summary>
        public int Post { get; set; }

        /// <summary>
        ///     Comment content.
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        ///     When the comment was created.
        /// </summary>
        public double Created { get; set; }

        /// <summary>
        ///     When the comment was lastly modified.
        /// </summary>
        public double? LastModified { get; set; }

        #endregion

        #region Foreign keys

        /// <summary>
        /// Detail information of comment owner.
        /// </summary>
        public virtual Account OwnerDetail { get; set; }

        /// <summary>
        /// Detail information of post which comment belongs to.
        /// </summary>
        public virtual Post PostDetail { get; set; }

        /// <summary>
        /// List of notifications broadcasted by comments.s
        /// </summary>
        public virtual ICollection<CommentNotification> CommentNotifications { get; set; }
        
        #endregion
    }
}