// <auto-generated />
namespace iConfess.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11212016001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11212016001));
        
        string IMigrationMetadata.Id
        {
            get { return "201611210907275_11212016001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
