// <auto-generated />
namespace iConfess.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170201001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170201001));
        
        string IMigrationMetadata.Id
        {
            get { return "201702011320531_20170201001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
